### ISSUE TITLE
reservedSeatTimeouts Memory Leak

### ISSUE THREAD

**Issue by amit-gshe** [colyseus/colyseus#285] opened 2019-11-30 10:32 UTC
We encountered a suspecious memory leak when using this framework, the `reservedSeatTimeouts` of `Room` seems not release in some unkown reasons. The cpu% will grow slowly from 1 to much higher. We inspected the heap dump and found the `reservedSeatTimeouts` of room stored so many `Timeout` instances. See below screenshot: ![leak screenshot](https://user-images.githubusercontent.com/7383028/69899190-e15d4200-139d-11ea-96b0-2ee228206853.png)
It seems in [this function](https://github.com/colyseus/colyseus/blob/5a8cbd16b8652e39ffbd29a6167b052f2c7fd025/src/Room.ts#L474) the `this.reservedSeatTimeouts` should delete the `reservedSeatTimeout`(`delete this.reservedSeatTimeouts[sessionId]`) when seats reservaltion expired.

**Comment by GDdark** [comment] 2019-12-20 00:57
me too. And I have to restart the server periodically.
I think it also leads to some rooms can not be disposed.

**Comment by GDdark** [comment] 2019-12-20 02:10
By the way...
Do you have a WeChat account?
Could I add you If you don't mind? My WeChat id is  GDdarked

Thanks!!!

@amit-gshe

**Comment by endel** [comment] 2019-12-20 02:24
Hi guys, on version `0.11.25` I've pushed this change, which may fix the memory leak: https://github.com/colyseus/colyseus/commit/49f1c9641411c09a4c26489f7a0bb85950baba5e

Regarding the rooms not being disposed, I do have the same issue on production for some projects, and I don't know exactly the reason yet. It never happens locally, so it's difficult to reproduce and find how to fix. The `@colyseus/monitor` often displays one room with `0` clients, and when I click on "inspect", there is one stale client in there.

**Comment by amit-gshe** [comment] 2019-12-20 02:47
@GDdark Sure. And in my case, I have an another severe mistake is that I used a `@colyseus` `Clock` instance in my schema instead of using the room's clock instance. Then I forgot to destroy the clock mannually which in result caused memory leak.

**Comment by endel** [comment] 2020-10-20 20:16
Closing as the original issue seems to have been resolved!

**Closed by endel** 2020-10-20 20:16 UTC
Labels: question
