### ISSUE TITLE
please help!onAdd and onRemove unable to trigger,but onStateChange can trigger.

### ISSUE THREAD

**Issue by a346573450** [colyseus/colyseus#786] opened 2024-10-25 01:21 UTC
### **Room.onStateChange can trigger ,but onAdd and onRemove Unable to trigger. No network requests received.
This problem has been bothering me for many days.
Can you give me some help? I hope to receive your guidance.thanks!**

### Steps to reproduce

**### This is client code**

### _**pic1**_
![1](https://github.com/user-attachments/assets/5d7ebe80-30f8-45b4-aba3-b0d3775d371d)

### **_pic2_**
![2](https://github.com/user-attachments/assets/3e2a6265-cc41-4806-ab9b-f54f10d83acd)
---------------------------------------------------------------------------

**### this is server code**

### _**pic1**_
![3](https://github.com/user-attachments/assets/8a9e9426-e497-4d57-9cf3-218647f20e83)

### _**pic2**_
![4](https://github.com/user-attachments/assets/9cf3b255-221f-4dea-838c-bdedc7eaddb2)

### _**pic3**_
![5](https://github.com/user-attachments/assets/95101ca7-7287-44ae-a453-10109f5714d4)

### Environment & Versions

Colyseus client:0.15.7
colyseus serve:0.15.7

**Comment by endel** [comment] 2024-10-25 01:31
Closing as this is duplicate of https://github.com/orgs/colyseus/discussions/787#discussioncomment-11046920

**Closed by endel** 2024-10-25 01:31 UTC
Labels: :bug: bug, :eyes: triage
