### ISSUE TITLE
"Uncaught Error: bad checksum" client issue

### ISSUE THREAD

**Issue by Escrichee** [colyseus/colyseus#392] opened 2020-12-21 14:05 UTC
Colyseus Version: 0.14.3
Colyseus.js Version: 0.14.1
Node.js Version: 12.0.0
Operating System and version: Mac OS X 10.14.6

Sometimes when the client calls the "joinOrCreate" function returns me a correct room but throws this error:

<img width="378" alt="Screenshot 2020-12-21 at 11 56 05" src="https://user-images.githubusercontent.com/12177312/102785984-19676680-439f-11eb-82d0-67193fb9ad91.png">

**Comment by endel** [comment] 2021-01-04 18:25
Hi @Escrichee, sorry for the delay to answer (I was on vacation for a few weeks)

Fossil Delta is going to be deprecated soon (https://github.com/colyseus/colyseus/issues/237), are you using it on purpose, or is this error happening without you using `this.setState()` at all? 

If you can share some source code it could help to find the cause. Cheers!

**Comment by endel** [comment] 2021-03-19 14:07
Closing, feel free to re-open if you're still having this issue

**Closed by endel** 2021-03-19 14:07 UTC
Labels: :grey_question: question
