### ISSUE TITLE
Unit test sample is not running

### ISSUE THREAD

**Issue by Flex301** [colyseus/colyseus#613] opened 2023-08-21 07:20 UTC
### Context

I'm trying to write the first tests for colyseus app, but running into a problem with the test setup.

### Bug description

```
TypeError: Cannot read properties of undefined (reading 'hgetall')

      14 |   it("connecting into a room", async() => {
      15 |     // `room` is the server-side Room instance reference.
    > 16 |     const room = await colyseus.createRoom("game_room", {});
         |                                 ^
      17 |
      18 |     const client1 = await colyseus.connectTo(room);
      19 |   });
```

### Steps to reproduce

I used testing samples from the colyseus docs.

https://docs.colyseus.io/tools/unit-testing/

### Environment & Versions

Colyseus: 0.14.23
Node: v16.14.2
OS: MacOS 13.5
Env: development

**Comment by endel** [comment] 2023-08-21 13:30
Hi @Flex301, can you provide a way to reproduce this error on my side? Thanks

**Comment by Flex301** [comment] 2023-08-21 18:08
@endel Sure. This is the full content of the test file.

```
import { ColyseusTestServer, boot } from "@colyseus/testing";

describe('Colyseus first test', () => {
  let colyseus: ColyseusTestServer;

  beforeAll(async () => {
    colyseus = await boot({});
  });
  afterAll(async () => await colyseus.shutdown());

  beforeEach(async () => await colyseus.cleanup());

  it("connecting into a room", async() => {
    // `room` is the server-side Room instance reference.
    const room = await colyseus.createRoom("game_room", {});

    const client1 = await colyseus.connectTo(room);
  });
});
```

I didn't add any assertions, just wanted to make sure the test is running like that. Also it's not clear if i need to provide some options to the `boot()`.

**Comment by endel** [comment] 2023-08-21 18:30
The `boot(...)` method requires either the whole configuration from your `app.config.ts` file, or a `Server` instance - you can see how this is used on a fresh app created via the app templates here: https://github.com/colyseus/create-colyseus-app/blob/master/templates/typescript/test/MyRoom_test.ts#L11

I've just tried providing `boot({})` as in your example and the error I got is the following:

```
ServerError: provided room name "game_room" not defined
```

This error is correct because there's no server reference defining such room during the `boot()`.

I'm curious why you've got this other error, though. If you can provide a full repo with the entire structure I could try to help out more. Cheers

**Comment by Flex301** [comment] 2023-08-21 20:38
@endel I've invited you to the repo. Please check it out.
Also I tried copying my project with only the game room and that test and that worked fine. So seems like something in my setup is wrong.

**Comment by endel** [comment] 2023-08-21 23:50
Hi @Flex301, just checked your sources - thanks for sharing. It turns out your issue seems to be having 0.14 packages installed along with 0.15 - causing conflicts on its internal dependencies. Sent you a pull-request there.

Every colyseus-related module must be at the same minor version. Closing this as doesn't seem to be a real issue. Feel free to reopen this issue, or reopen another one if you need! Cheers

**Closed by endel** 2023-08-21 23:50 UTC
Labels: :bug: bug, :eyes: triage

**Comment by Flex301** [comment] 2023-08-22 07:09
Thank you so much @endel. Now it’s running the test.
